src/blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.BlogView.as_view(), name='blog'),
    path('posts/<slug:blog_slug>/', views.BlogDetailView.as_view(), name='blog_detail'),
    path('posts/category/<slug:category_blog_slug>/', views.CategoryBlogView.as_view(), name='category_blog'),
    path('like/', views.post_like, name='post_like'),
]

src/pet_care_scheduler/urls.py
from django.urls import path
from . import views

app_name = 'schedule'

urlpatterns = [
    # path('orders/confirmed/<slug:service_slug>/', views.confirm_filter_orders, name='confirm_filter_orders'),
    path('orders/draft/', views.DraftOrders.as_view(), name='draft_orders'),
    path('orders/completed/', views.CompletedOrders.as_view(), name='completed_orders'),
    path('orders/confirmed/', views.ConfirmedOrders.as_view(), name='confirmed_orders'),
    path('orders/postponed/', views.DelayedOrders.as_view(), name='delayed_orders'),
    path('orders/', views.ShowOrders.as_view(), name='show_orders'),
    path('user-orders/<str:user_username>/', views.UserOrders.as_view(), name='show_user_orders'),
    path('orders/detail/<int:order_id>/', views.OrderDetail.as_view(), name='order_detail'),
    path('orders/edit/<int:order_id>/', views.OrderEdit.as_view(), name='order_edit'),
    path('orders/<int:order_id>/complete/', views.CompleteOrder.as_view(), name='complete_order'),
    path('orders/<int:order_id>/confirm/', views.ConfirmOrder.as_view(), name='confirm_order'),
    path('orders/<int:order_id>/delay/', views.DelayOrder.as_view(), name='delay_order'),
    path('orders/<int:order_id>/postpone/', views.PostponeOrder.as_view(), name='postpone_order'),
    path('orders/<slug:service_slug>/', views.FilterOrders.as_view(), name='show_filter_orders'),
]

src/project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('vet_clinic.urls', namespace='vet_clinic')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('schedule/', include('pet_care_scheduler.urls', namespace='schedule')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('__debug__/', include('debug_toolbar.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/vet_clinic/urls.py
from django.urls import path
from . import views

app_name = 'vet_clinic'

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('about/', views.about, name='about'),
    path('services/', views.ServicesView.as_view(), name='services'),
    path('services/<slug:service_slug>/', views.ServiceDetailView.as_view(), name='service_detail'),
    path('faq/', views.faq, name='faq'),
    path('responses/', views.responses, name='responses'),
    path('contacts/', views.contacts, name='contacts'),
    path('contacts/<slug:service_slug>/', views.contacts, name='contacts_detail'),
]

src/blog/models.py
from django.conf import settings
from django.db import models
from django.urls import reverse


class Post(models.Model):
    title = models.CharField(max_length=50)
    slug = models.SlugField(max_length=50, unique=True, db_index=True)
    description = models.TextField(blank=True)
    content = models.TextField(blank=True)
    photo = models.ImageField(upload_to='posts/%Y/%m/%d/', blank=True, null=True, default=None)
    users_like = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='users_like', blank=True)
    publish_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)
    is_published = models.BooleanField(default=True)
    category = models.ForeignKey('Category', on_delete=models.PROTECT, related_name='post_category', null=True)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Post'
        verbose_name_plural = 'Posts'
        ordering = ['-publish_date']
        indexes = [
            models.Index(fields=['-publish_date']),
        ]

    def get_absolute_url(self):
        return reverse("blog:blog_detail", kwargs={"blog_slug": self.slug})


class Category(models.Model):
    name = models.CharField(max_length=50, db_index=True)
    slug = models.SlugField(max_length=50, unique=True, db_index=True)

    class Meta:
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("blog:category_blog", kwargs={"category_blog_slug": self.slug})


class Comment(models.Model):
    name = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='comment_name')
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comment_post')
    comm_content = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ['-created']
        indexes = [
            models.Index(fields=['created'])
        ]

    def __str__(self):
        return f'Comment by {self.name} on {self.post}'

src/vet_clinic/models.py
from django.conf import settings
from django.contrib.auth import get_user_model
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse
from phonenumber_field.modelfields import PhoneNumberField


class Service(models.Model):
    title = models.CharField(max_length=50)
    slug = models.SlugField(max_length=50, unique=True, db_index=True)
    description = models.TextField(blank=True)
    content = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    photo = models.ImageField(upload_to='services/%Y/%m/%d/', blank=True, null=True, default=None)
    publish_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)
    is_published = models.BooleanField(default=True)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Service'
        verbose_name_plural = 'Services'
        ordering = ['-price']
        indexes = [
            models.Index(fields=['-price']),
        ]

    def get_absolute_url(self):
        return reverse("vet_clinic:service_detail", kwargs={"service_slug": self.slug})


class Testimonial(models.Model):
    name = models.CharField(max_length=50, db_index=True)
    slug = models.SlugField(max_length=50, unique=True, db_index=True)
    response = models.TextField(max_length=500, blank=True)
    publish_date = models.DateTimeField(auto_now_add=True)
    is_published = models.BooleanField(default=True)

    class Meta:
        verbose_name = 'Testimonial'
        verbose_name_plural = 'Testimonials'
        ordering = ['-publish_date']
        indexes = [
            models.Index(fields=['-publish_date']),
        ]

    def __str__(self):
        return self.name

src/blog/forms.py
from django import forms

from .models import Comment


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['comm_content']
        widgets = {
            'comm_content': forms.Textarea(attrs={'cols': 10, 'rows': 1, 'class': 'contacts-form__input-response',
                                                  'placeholder': "Enter your response"})
        }

src/vet_clinic/forms.py
from django import forms
from phonenumber_field.widgets import PhoneNumberPrefixWidget
from .models import Testimonial
from django.utils.text import slugify


class TestimonialAddForm(forms.ModelForm):
    class Meta:
        model = Testimonial
        fields = ['name', 'response', 'is_published']
        widgets = {
            'name': forms.TextInput(
                attrs={'class': 'contacts-form__input-name', 'placeholder': 'Enter your full name'}),
            'response': forms.Textarea(attrs={'cols': 50, 'rows': 10, 'class': 'contacts-form__input-response',
                                              'placeholder': "Enter your response"})
        }

    def save(self, commit=True):
        instance = super(TestimonialAddForm, self).save(commit=False)
        instance.slug = slugify(instance.name)

        if commit:
            instance.save()
        return instance

src/blog/views.py
import logging

import redis
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
from django.shortcuts import render, get_object_or_404, redirect
from django.views.decorators.http import require_POST
from django.views.generic import ListView, DetailView
from django.views.generic.edit import ModelFormMixin

from actions.utils import create_action
from vet_clinic.utils import DataMixin
from .forms import CommentForm
from .models import Post, Category


logger = logging.getLogger('blog')

r = redis.Redis(host=settings.REDIS_HOST, port=settings.REDIS_PORT, db=settings.REDIS_DB)


class BlogView(DataMixin, ListView):
    context_object_name = 'posts'
    template_name = 'blog/blog.html'
    paginate_by = 6

    def get_queryset(self):
        return Post.objects.all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return self.get_mixin_context(context, title='Blog')


class BlogDetailView(DataMixin, ModelFormMixin, DetailView):
    template_name = 'blog/blog_detail.html'
    context_object_name = 'post'
    slug_url_kwarg = 'blog_slug'
    form_class = CommentForm

    def get_object(self, queryset=None):
        return get_object_or_404(Post, slug=self.kwargs[self.slug_url_kwarg])

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        try:
            context['total_views'] = r.incr(f'post:{self.get_object().id}:views')
        except:
            logger.info('redis db is not loaded')
        context['comments'] = self.get_object().comment_post.filter(active=True)  # check related name
        return self.get_mixin_context(context, title=context['post'].title)

    def post(self, request, *args, **kwargs):
        form = CommentForm(request.POST)
        if form.is_valid():
            new_comment = form.save(commit=False)
            new_comment.post = self.get_object()
            new_comment.name = request.user
            new_comment.save()
            create_action(request.user, 'commented post', new_comment.post)
            logger.info(f'{request.user.username} has commented a post')
            return redirect('blog:blog_detail', blog_slug=self.kwargs[self.slug_url_kwarg])


@login_required
@require_POST
def post_like(request):
    post_id = request.POST.get('id')
    action = request.POST.get('action')

    if post_id and action:
        try:
            post = Post.objects.get(id=post_id)
            if action == 'like':
                post.users_like.add(request.user)
                create_action(request.user, 'likes', post)
                logger.info(f'{request.user.username} has liked a post')
            else:
                post.users_like.remove(request.user)
                logger.info(f'{request.user.username} has disliked a post')
            return JsonResponse({'status': 'ok'})
        except Post.DoesNotExists:
            pass
            logger.warning(f'post does not exist')
    return JsonResponse({'status': 'error'})


class CategoryBlogView(ListView):
    model = Category
    template_name = 'blog/blog.html'
    context_object_name = 'posts'
    allow_empty = False

    def get_queryset(self):
        # category_slug from its url
        return Post.objects.filter(category__slug=self.kwargs['category_blog_slug']).select_related('category')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        category = context['posts'].first().category  # from queryset first item then its category
        context['title'] = 'Category - ' + category.name  # name from category
        return context

src/vet_clinic/views.py
import logging

from django.conf import settings
from django.contrib import messages
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.http import HttpResponse, JsonResponse
from django.shortcuts import render, get_object_or_404, redirect

from django.views.decorators.http import require_POST
from django.views.generic import ListView, DetailView
from django.views.generic.edit import ModelFormMixin

from accounts.models import StaffProfile
from actions.utils import create_action
from pet_care_scheduler.forms import ScheduleForm
from .forms import TestimonialAddForm
from .models import Service, Testimonial
from .utils import DataMixin


logger = logging.getLogger('vet_clinic')


class HomeView(DataMixin, ListView):
    context_object_name = 'services_list'
    template_name = 'vet_clinic/index.html'

    def get_queryset(self):
        return Service.objects.all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return self.get_mixin_context(context, title='Home')


class ServicesView(DataMixin, ListView):
    context_object_name = 'services_list'
    template_name = 'vet_clinic/services.html'

    def get_queryset(self):
        return Service.objects.all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return self.get_mixin_context(context, title='Services')


class ServiceDetailView(DataMixin, ModelFormMixin, DetailView):
    # model = Service
    template_name = 'vet_clinic/service_detail.html'
    context_object_name = 'service'
    slug_url_kwarg = 'service_slug'  # from url
    form_class = ScheduleForm

    def get_object(self, queryset=None):
        return get_object_or_404(Service, slug=self.kwargs[self.slug_url_kwarg])

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return self.get_mixin_context(context, title=context['service'].title)

    def post(self, request, *args, **kwargs):
        form = ScheduleForm(request.POST)
        if form.is_valid():
            new_order = form.save(commit=False)
            new_order.service = self.get_object()
            new_order.name = request.user
            new_order.save()
            create_action(request.user, 'makes order', new_order)
            logger.info(f'{request.user.username} has made an order')
            return redirect('vet_clinic:services')


def faq(request):
    return HttpResponse('faq')


def responses(request):
    responses_list = Testimonial.objects.all()

    paginator = Paginator(responses_list, 6)
    page_number = request.GET.get('page', 1)
    responses_list = paginator.page(page_number)

    if request.method == 'POST':
        form = TestimonialAddForm(request.POST)
        if form.is_valid():
            form.save()
            logger.info(f'{request.user.username} response')
            return redirect('vet_clinic:responses')
    else:
        form = TestimonialAddForm()

    data = {
        'responses_list': responses_list,
        'form': form,
        'default_service': settings.DEFAULT_USER_IMAGE
    }
    return render(request, 'vet_clinic/responses.html', context=data)


def contacts(request):
    return render(request, 'vet_clinic/contacts.html')


def about(request):
    staff = get_user_model().objects.filter(groups__name='doctors')

    data = {
        'staff': staff,
        'default_profile': settings.DEFAULT_PROFILE_IMAGE
    }

    return render(request, 'vet_clinic/about-us.html', context=data)

src/vet_clinic/templates/vet_clinic/about-us.html
{% extends 'base.html' %}

{% block content %}
<div class="container-background">
    <main>
        <section class="about">
            <div class="about__title container">
                <h2 class="about__heading">About Us</h2>
                <p class="about__contact">
                    Order our services now!
                    <a href="#" class="about__phone">+ 1 (234) 567 89 00</a>
                </p>
            </div>
        </section>
        <section class="intro container">
            <div class="intro__content">
                <h1 class="intro__heading">
                    Your Fluffy Friend Is In Our Safe And Caring Hands
                </h1>
                <span class="intro__subtitle"
                >We are a small firm with 15 dedicated employees that provide all
              kinds of pet care services in New York.</span
                >
                <div class="intro__description">
                    <p class="intro__paragraph">
                        We know how much you adore your pet. You can be sure that we
                        care about your family member with all our attention and love
                        for animals. We offer all kinds of pet care services for our
                        clients in New York.
                    </p>
                    <p class="intro__paragraph">
                        Our dedicated team of vets, groomers, pet sitters and other
                        specialists will provide all kinds of services and take care of
                        your pet. We find an approach to every animal. You can rest
                        assured that your fluffy family member will stay healthy and
                        happy.
                    </p>
                </div>
                <div class="intro__buttons">
                    <a class="intro__button" href="{% url 'vet_clinic:services' %}">Our Services</a>
                </div>
            </div>
        </section>
        <div class="meet_our_team__partial">
            <section class="team container">
                <div class="team__info">
                    <h2 class="team__title">Meet Our Team</h2>
                    <p class="team__description">Each member of our Best.Pet family loves animals and is trained to look
                        after them.
                    </p>
                    <div class="row row-cols-1 row-cols-md-2 g-4">
                        {% for s in staff %}
                        <div class="col">
                            <div class="card mx-auto mb-3" style="background-color: var(--background-color); min-height: 280px">
                                <h5 class="card-header" style="color: var(--bright-text-color);">{{ s.position }}</h5>
                                <div class="row g-0">
                                    {% if s.profile.photo %}
                                    <div class="col-md-4">
                                        <img src="{{ s.profile.photo.url }}" class="img-fluid rounded-start"
                                             alt="...">
                                    </div>
                                    {% else %}
                                    <div class="col-md-4">
                                        <img src="{{ default_profile }}" class="img-fluid rounded-start"
                                             alt="...">
                                    </div>
                                    {% endif %}
                                    <div class="col-md-8">
                                        <div class="card-body">
                                            <h5 class="card-title" style="color: var(--title-text-color);">{{ s.first_name }} {{ s.last_name }}</h5>
                                            <p class="card-text" style="color: var(--subtitle-text-color);">{{ s.staffprofile.description }}</p>
<!--                                            <p class="card-text"><small class="text-body-secondary">Last updated 3 mins-->
<!--                                                ago</small></p>-->
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        {% endfor %}
                    </div>
                </div>
            </section>
        </div>
    </main>
</div>
{% endblock %}

src/vet_clinic/templates/vet_clinic/blog_detail.html
{% extends 'base.html' %}

{% block content %}
<div class="container-background">
    <main>
        <section class="vet-consultations">
            <div class="vet-consultations__title container">
                <h1>{{post.title}}</h1>
                <!--                <p>Order our services now! <a href="#">+ 1 (234) 567 89 00</a></p>-->
            </div>
        </section>
        <section class="consultations">
            <div class="consultations__description container">
                <div class="consultations__description-right-item">
                    {% if post.photo %}
                    <p><img src="{{ post.photo.url }}"></p>
                    {% else %}
                    <p><img src="{{ default_service }}" class="services-carousel__img"></p>
                    {% endif %}
                </div>
                {% with total_likes=post.users_like.count users_like=post.users_like.all %}
                <div class="consultations__description-left-item">
                    <h2>{{post.title}}</h2>
                    <h3>Read about:</h3>
                    <p>{{post.description}}</p>
                    <span class="count">
                        <span class="total">{{ total_likes }}</span>
                        like{{ total_likes|pluralize }}
                    </span>
                    {% if user.is_authenticated %}
                    <a href="#" data-id="{{ post.id }}"
                       data-action="{% if request.user in users_like %}un{% endif %}like"
                       class="like button">
                        {% if request.user not in users_like %}
                        Like
                        {% else %}
                        Unlike
                        {% endif %}
                    </a>
                    {% endif %}
                </div>
                {% endwith %}
            </div>
            <div class="consultations__text container">
                <p>{{ post.content|linebreaksbr }}</p>
            </div>

            <div class="contacts-help-section__form-container ">
                <div class="contacts-help-section__wrapper">
                    {% if user.is_authenticated %}
                    <form class="contacts-form" action="#" method="post" enctype="multipart/form-data">
                        <div class="responses__form-title">
                            <h3>Please, leave comment using the following form</h3>
                        </div>
                        <div class="contacts-form__field">
                            <div class="contacts-form__field">
                                {{ form.as_p }}
                                {% csrf_token %}
                            </div>
                        </div>
                        <div class="contacts-form__field">
                            <input type="hidden" name="next" value="{{ next }}"/>
                            <button class="contacts-form__button" type="submit">Send</button>
                        </div>
                    </form>
                    {% else %}
                    <div class="responses__form-title">
                        <h3>Please, login to leave a comment</h3>
                    </div>
                    {% endif %}
                </div>
            </div>


            {% for comment in comments %}
            <div class="card mb-3 container">
                <div class="card-body">
                    <h5 class="card-title">{{ comment.name }}</h5>
                    <p class="card-text">{{ comment.comm_content }}</p>
                    <p class="card-text"><small class="text-muted">{{ comment.created }}</small></p>
                </div>
            </div>
            {% endfor %}
        </section>
    </main>
</div>
{% endblock %}

{% block domready %}
const url = '{% url "vet_clinic:post_like" %}';
var options = {
method: 'POST',
headers: {'X-CSRFToken': csrftoken},
mode: 'same-origin'
}

document.querySelector('a.like')
.addEventListener('click', function(e){
e.preventDefault();
var likeButton = this;

// add request body
var formData = new FormData();
formData.append('id', likeButton.dataset.id);
formData.append('action', likeButton.dataset.action);
options['body'] = formData;

// send HTTP request
fetch(url, options)
.then(response => response.json())
.then(data => {
if (data['status'] === 'ok')
{
var previousAction = likeButton.dataset.action;

// toggle button text and data-action
var action = previousAction === 'like' ? 'unlike' : 'like';
likeButton.dataset.action = action;
likeButton.innerHTML = action;

// update like count
var likeCount = document.querySelector('span.count .total');
var totalLikes = parseInt(likeCount.innerHTML);
likeCount.innerHTML = previousAction === 'like' ? totalLikes + 1 : totalLikes - 1;
}
})
});
{% endblock %}

src/vet_clinic/templates/vet_clinic/category_blog.html
<div class="categories">
    <p class="categories__item">
        <a href="{% url 'vet_clinic:blog' %}" class="categories__link">All</a>
    </p>
    {% for category in categories %}
    <p class="categories__item">
        <a href="{{ category.get_absolute_url }}" class="categories__link">{{ category.name }}</a>
    </p>
    {% endfor %}
</div>

src/vet_clinic/templates/vet_clinic/order-detail.html
{% extends 'base.html' %}

{% block content %}
{% if perms.order.view_order %}

<div class="container">
    <div class="row">
        <div class="mx-auto">
            {% if messages %}
            {% for message in messages %}
            {% if message.level == DEFAULT_MESSAGE_LEVELS.SUCCESS %}
            <div class="alert alert-success alert-dismissible fade show" role="alert">
                {{ message }}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
            {% else %}
            <div class="alert alert-warning alert-dismissible fade show" role="alert">
                {{ message }}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
            {% endif %}
            {% endfor %}
            {% endif %}
        </div>
    </div>
</div>

<div class="card container mb-3">
    <div class="card-header">
        <ul class="nav nav-pills card-header-pills">
            <li class="nav-item mx-2">
                <form action="{% url 'vet_clinic:complete_order' order.id %}" method="post">
                    {% csrf_token %}
                    <button class="btn btn-outline-danger" type="submit">Complete</button>
                </form>
            </li>
            <li class="nav-item mx-2">
                <form action="{% url 'vet_clinic:confirm_order' order.id %}" method="post">
                    {% csrf_token %}
                    <button class="btn btn-success" type="submit">Confirm</button>
                </form>
            </li>
            <li class="nav-item mx-2">
                <form action="{% url 'vet_clinic:delay_order' order.id %}" method="post">
                    {% csrf_token %}
                    <button class="btn btn-warning" type="submit">Delay</button>
                </form>
            </li>
            <li class="nav-item mx-1">
                <a class="nav-link" href="#">Link</a>
            </li>
            <li class="nav-item">
                <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
            </li>
        </ul>
    </div>

    <div class="card-body my-2">
        <h3 class="card-title">service: {{ order.service }}</h3>
        <p class="card-text">nickname: {{ order.name }}</p>
        <p class="card-text">First and last name: {{ order.name.first_name }} {{ order.name.last_name }}</p>
        <p class="card-text">Phone Number: {{ order.phone_number }}</p>
        <p class="card-text">About Pet: {{ order.pet_info }}</p>
        <p class="card-text">Order date: {{ order.order_date }}</p>
        <p class="card-text">Client date for visiting: {{ order.date_for_visit }}</p>
        <a href="{{ order.get_absolute_url }}" class="btn btn-primary">Go somewhere</a>
    </div>
</div>
{% endif %}
{% endblock %}

src/vet_clinic/templates/vet_clinic/orders.html
{% extends "base.html" %}

{% block content %}
<div class="vet-consultations__title container">
    <h1>Orders</h1>
</div>

{% if perms.order.view_order %}

<ul class="nav nav-tabs container mb-5 fs-5">
    <li class="nav-item">
        <a class="nav-link active" aria-current="page" href="{% url 'vet_clinic:show_orders' %}">All</a>
    </li>
    <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-expanded="false">Services</a>
        <ul class="dropdown-menu">
            {% for service in services_list %}
            <li>
                <a class="dropdown-item" href="{% url 'vet_clinic:show_filter_orders' service.slug %}">{{ service.title }}</a>
            </li>
            {% endfor %}
            <li>
                <hr class="dropdown-divider">
            </li>
            <li><a class="dropdown-item" href="#">#</a></li>
        </ul>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="{% url 'vet_clinic:draft_orders' %}">Draft</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="{% url 'vet_clinic:completed_orders' %}">Completed</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="{% url 'vet_clinic:confirmed_orders' %}">Confirmed</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="{% url 'vet_clinic:delayed_orders' %}">Postponed</a>
    </li>
    <li class="nav-item">
        <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
    </li>
</ul>


{% for order in orders %}
<div class="card {% if order.status == 'CMP' %}border-danger{% elif order.status == 'CNF' %}border-success{% elif order.status == 'DLY' %}border-warning{% else %}border-primary{% endif %} border-3 container mb-3">
    <div class="card-body my-2">
        <h3 class="card-title">service: {{ order.service }}</h3>
        <p class="card-text">nickname: {{ order.name }}</p>
        <p class="card-text">First and last name: {{ order.name.first_name }} {{ order.name.last_name }}</p>
        <p class="card-text">Phone Number: {{ order.phone_number }}</p>
        <p class="card-text">About Pet: {{ order.pet_info }}</p>
        <p class="card-text">Order date: {{ order.order_date }}</p>
        <p class="card-text">Client date for visiting: {{ order.date_for_visit }}</p>
        <p class="card-text">Client date for visiting: {{ order.status }}</p>
        <a href="{{ order.get_absolute_url }}" class="btn btn-primary">Details</a>
    </div>
</div>

{% endfor %}
{% endif %}
{% endblock %}