src/accounts/urls.py
from django.contrib.auth.views import PasswordChangeDoneView, PasswordResetView, PasswordResetDoneView, \
    PasswordResetConfirmView, PasswordResetCompleteView
from django.urls import path, reverse_lazy
from . import views

app_name = 'accounts'

urlpatterns = [
    path('login/', views.LoginUser.as_view(), name='login'),
    path('logout/', views.LogoutUser.as_view(), name='logout'),

    path('register/', views.register, name='register'),

    path('password-change/', views.UserChangePassword.as_view(), name='password_change'),
    path('password-change_done/', PasswordChangeDoneView.as_view(template_name='accounts/password_change_done.html'),
         name='password_change_done'),

    path('password-reset/', PasswordResetView.as_view(
        template_name='accounts/password_reset_form.html',
        email_template_name='accounts/password_reset_email.html',
        success_url=reverse_lazy('accounts:password_reset_done')
    ), name='password_reset'),
    path('password-reset/done/', PasswordResetDoneView.as_view(template_name='accounts/password_reset_done.html'),
         name='password_reset_done'),
    path('password-reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(
        template_name='accounts/password_reset_form.html',
        success_url=reverse_lazy('accounts:password_reset_complete')
    ), name='password_reset_confirm'),
    path('password-reset/complete/', PasswordResetCompleteView.as_view(template_name='accounts/password_reset_complete.html'),
         name='password_reset_complete'),

    path('edit/', views.edit, name='edit'),

    path('profile/<str:user_username>/', views.profile_to_view, name='profile_to_view'),
]

src/blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.BlogView.as_view(), name='blog'),
    path('posts/<slug:blog_slug>/', views.BlogDetailView.as_view(), name='blog_detail'),
    path('posts/category/<slug:category_blog_slug>/', views.CategoryBlogView.as_view(), name='category_blog'),
    path('like/', views.post_like, name='post_like'),
]

src/project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('vet_clinic.urls', namespace='vet_clinic')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('schedule/', include('pet_care_scheduler.urls', namespace='schedule')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('__debug__/', include('debug_toolbar.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/vet_clinic/urls.py
from django.urls import path
from . import views

app_name = 'vet_clinic'

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('about/', views.about, name='about'),
    path('services/', views.ServicesView.as_view(), name='services'),
    path('services/<slug:service_slug>/', views.ServiceDetailView.as_view(), name='service_detail'),
    path('faq/', views.faq, name='faq'),
    path('responses/', views.responses, name='responses'),
    path('contacts/', views.contacts, name='contacts'),
    path('contacts/<slug:service_slug>/', views.contacts, name='contacts_detail'),
]

src/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ title|default:"Best.Pet" }}</title>
    <link rel="shortcut icon" href="img/icon-website.png" type="image/x-icon">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"></script>
    <link rel="stylesheet" href="{% static 'vet_clinic/css/index.css' %}">
    <script type="module" src="{% static 'vet_clinic/js/index.js' %}"></script>
</head>
<body>
<div class="container-background">
    {% block mainmenu %}
    <header class="header">
        <div class="header__wrapper">
            <div class="header__content">
                <div class="header__top">
                    <a href="{% url 'vet_clinic:home' %}" class="header__top-logo-link">
                        <img class="header__top-logo" src="{% static 'vet_clinic/img/top-bar-logo.svg' %}"
                             alt="Logo Best Pet - safe and caring hands">
                    </a>
                    <nav class="nav">
                        <ul class="header__nav-list nav__list">
                            {% for m in mainmenu %}
                            <li class="nav__item"><a class="nav__link" href="{% url m.url_name %}">{{m.title}}</a>
                            </li>
                            {% endfor %}
                        </ul>
                    </nav>
                    <nav class="navbar navbar-expand-lg navbar-light bg-light">
                        <div class="container-fluid">
                            <div class="collapse navbar-collapse" id="navbarNav">
                                <ul class="navbar-nav">
                                    {% if user.is_authenticated %}
                                    <li class="nav-item">
                                        <a class="nav-link active" aria-current="page"
                                           href="{% url 'accounts:profile_to_view' user_username=user.username %}">
                                            {{ user.username }}
                                        </a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link" href="{% url 'accounts:edit' %}">
                                            Edit
                                        </a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link" href="#">
                                            <form method="post" action="{% url 'accounts:logout' %}">
                                                {% csrf_token %}
                                                <button type="submit">Logout</button>
                                            </form>
                                        </a>
                                    </li>
                                    {% else %}
                                    <li class="nav-item">
                                        <a class="nav-link active" aria-current="page"
                                           href="{% url 'accounts:login' %}">
                                            Login
                                        </a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link" href="{% url 'accounts:register' %}">
                                            Register
                                        </a>
                                    </li>
                                    {% endif %}
                                </ul>
                            </div>
                        </div>
                    </nav>
                    <div class="header__top-icons">
                        <a href="S" class="header__menu-btn">
                            <span class="header__navicon"></span>
                        </a>
                        <a href="https://www.facebook.com/" class="header__top-icons-link">
                            <img class="footer__social-image" src="{% static 'vet_clinic/img/social_facebook.svg' %}"
                                 alt="Footer Logo">
                        </a>
                        <a href="https://www.instagram.com/" class="header__top-icons-link">
                            <img class="footer__social-image" src="{% static 'vet_clinic/img/social_instagram.svg' %}"
                                 alt="Footer Logo">
                        </a>
                        <a href="https://www.twitter.com/" class="header__top-icons-link">
                            <img class="footer__social-image" src="{% static 'vet_clinic/img/social_twitter.svg' %}"
                                 alt="Footer Logo">
                        </a>
                        <a href="https://www.youtube.com/" class="header__top-icons-link">
                            <img class="footer__social-image" src="{% static 'vet_clinic/img/social_youtube.svg' %}"
                                 alt="Footer Logo">
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </header>
    {% endblock mainmenu %}
    {% block content %}
    {% endblock %}

    {% block footer %}
    <div class="footer">
        <nav class="footer__nav">
            <ul class="footer__nav-list">
                <li class="menu-item">
                    <img class="footer__logo-image" src="{% static 'vet_clinic/img/logofooter.svg' %}"
                         alt="Footer Logo">
                    <p class="footer-text">We care about every pet of our clients and provide all kinds of pet care
                        services in New York.</p>
                    <div class="footer__social-icons">
                        <a href="https://www.facebook.com/" class="footer__social-link">
                            <img class="footer__social-image" src="{% static 'vet_clinic/img/social_facebook.svg' %}"
                                 alt="Footer Logo">
                        </a>
                        <a href="https://www.instagram.com/" class="footer__social-link">
                            <img class="footer__social-image" src="{% static 'vet_clinic/img/social_instagram.svg' %}"
                                 alt="Footer Logo">
                        </a>
                        <a href="https://www.twitter.com/" class="footer__social-link">
                            <img class="footer__social-image" src="{% static 'vet_clinic/img/social_twitter.svg' %}"
                                 alt="Footer Logo">
                        </a>
                        <a href="https://www.youtube.com/" class="footer__social-link">
                            <img class="footer__social-image" src="{% static 'vet_clinic/img/social_youtube.svg' %}"
                                 alt="Footer Logo">
                        </a>
                    </div>
                </li>
                <li class="menu-item">
                    <h3 class="menu-item-title">Navigation</h3>
                    <div class="menu-item-link-countainer">
                        {% for f in footer_nav %}
                        <a class="menu-item-link" href="{% url f.url_name %}">{{f.title}}</a>
                        {% endfor %}
                    </div>
                </li>
                <li class="menu-item">
                    <h3 class="menu-item-title">Qiuck Links</h3>
                    <div class="menu-item-link-countainer">
                        {% for f in footer_links %}
                        <a class="menu-item-link" href="{% url f.url_name %}">{{f.title}}</a>
                        {% endfor %}
                    </div>
                </li>
                <li class="menu-item">
                    <h3 class="menu-item-title">Support</h3>
                    <div class="menu-item-link-countainer">
                        {% for f in footer_support %}
                        <a class="menu-item-link" href="{% url f.url_name %}">{{f.title}}</a>
                        {% endfor %}
                    </div>
                </li>
                <li class="menu-item">
                    <h3 class="menu-item-title">Subscribe</h3>
                    <div class="menu-item-link-countainer">
                        <form action="#" class="footer-form">
                            <label for="leave-your-email:" class="footer-label-text">
                                Leave your email:
                            </label>
                            <input type="email" placeholder="Email*" name="leave-your-email" id="leave-your-email"
                                   class="footer-input-form">
                            <button class="footer-form__button" type="submit">Subscribe</button>
                        </form>
                    </div>
                </li>
            </ul>
        </nav>
    </div>
    {% endblock footer %}
</div>
</body>
<script src="//cdn.jsdelivr.net/npm/js-cookie@3.0.1/dist/js.cookie.min.js"></script>
<script>
    const csrftoken = Cookies.get('csrftoken');
    document.addEventListener('DOMContentLoaded', (event) => {
    // DOM loaded
    {% block domready %}
    {% endblock %}
    })
</script>
</html>