src/blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.BlogView.as_view(), name='blog'),
    path('posts/<slug:blog_slug>/', views.BlogDetailView.as_view(), name='blog_detail'),
    path('posts/category/<slug:category_blog_slug>/', views.CategoryBlogView.as_view(), name='category_blog'),
    path('like/', views.post_like, name='post_like'),
]

src/pet_care_scheduler/urls.py
from django.urls import path
from . import views

app_name = 'schedule'

urlpatterns = [
    # path('orders/confirmed/<slug:service_slug>/', views.confirm_filter_orders, name='confirm_filter_orders'),
    path('orders/draft/', views.DraftOrders.as_view(), name='draft_orders'),
    path('orders/completed/', views.CompletedOrders.as_view(), name='completed_orders'),
    path('orders/confirmed/', views.ConfirmedOrders.as_view(), name='confirmed_orders'),
    path('orders/postponed/', views.DelayedOrders.as_view(), name='delayed_orders'),
    path('orders/', views.ShowOrders.as_view(), name='show_orders'),
    path('user-orders/<str:user_username>/', views.UserOrders.as_view(), name='show_user_orders'),
    path('orders/detail/<int:order_id>/', views.OrderDetail.as_view(), name='order_detail'),
    path('orders/edit/<int:order_id>/', views.OrderEdit.as_view(), name='order_edit'),
    path('orders/<int:order_id>/complete/', views.CompleteOrder.as_view(), name='complete_order'),
    path('orders/<int:order_id>/confirm/', views.ConfirmOrder.as_view(), name='confirm_order'),
    path('orders/<int:order_id>/delay/', views.DelayOrder.as_view(), name='delay_order'),
    path('orders/<int:order_id>/postpone/', views.PostponeOrder.as_view(), name='postpone_order'),
    path('orders/<slug:service_slug>/', views.FilterOrders.as_view(), name='show_filter_orders'),
]

src/project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('vet_clinic.urls', namespace='vet_clinic')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('schedule/', include('pet_care_scheduler.urls', namespace='schedule')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('__debug__/', include('debug_toolbar.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/pet_care_scheduler/models.py
from django.conf import settings
from django.db import models
from django.urls import reverse
from phonenumber_field.modelfields import PhoneNumberField

from vet_clinic.models import Service


class Schedule(models.Model):
    class Status(models.TextChoices):
        DRAFT = 'DRF', 'Draft'
        COMPLETE = 'CMP', 'Complete'
        CONFIRM = 'CNF', 'Confirm'
        DELAY = 'DLY', 'Delay'

    name = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='client_name')
    phone_number = PhoneNumberField()
    pet_info = models.CharField(max_length=50)
    service = models.ForeignKey(Service, on_delete=models.CASCADE, related_name='service_name')
    order_date = models.DateTimeField(auto_now_add=True)
    date_for_visit = models.DateField()
    status = models.CharField(max_length=3, choices=Status.choices, default=Status.DRAFT)

    class Meta:
        verbose_name = 'Schedule'
        verbose_name_plural = 'Schedule'
        ordering = ['-order_date']
        indexes = [
            models.Index(fields=['-order_date']),
        ]

    def get_absolute_url(self):
        return reverse("schedule:order_detail", kwargs={"order_id": self.id})

    def __str__(self):
        return f'Order by {self.name}'

src/pet_care_scheduler/forms.py
from django import forms
from phonenumber_field.widgets import PhoneNumberPrefixWidget

from .models import Schedule


class ScheduleForm(forms.ModelForm):
    date_for_visit = forms.DateField(widget=forms.widgets.DateInput(attrs={'class': 'contacts-form__input-service',
                                                                           'type': 'date'}))

    class Meta:
        model = Schedule
        fields = ['phone_number', 'pet_info', 'date_for_visit']
        widgets = {
            'phone_number': PhoneNumberPrefixWidget(attrs={'class': 'contacts-form__input-service'}, initial='UA'),
            'pet_info': forms.TextInput(
                attrs={'class': 'contacts-form__input-service', 'placeholder': "Pet's name and age"}),
        }

src/pet_care_scheduler/views.py
import logging

from django.contrib import messages
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse, reverse_lazy
from django.views import View
from django.views.generic import ListView, DetailView, FormView, UpdateView

from .forms import ScheduleForm
from .models import Schedule
from vet_clinic.models import Service

logger = logging.getLogger('pet_care_scheduler')


class ShowOrders(PermissionRequiredMixin, ListView):
    context_object_name = 'orders'
    template_name = 'pet_care_scheduler/orders.html'
    permission_required = 'pet_care_scheduler.view_schedule'

    def get_queryset(self):
        return Schedule.objects.exclude(status=Schedule.Status.COMPLETE)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['services_list'] = Service.objects.all()
        return context


class OrderEdit(PermissionRequiredMixin, DetailView):
    model = Schedule
    template_name = 'pet_care_scheduler/order-edit.html'
    context_object_name = 'order'
    slug_url_kwarg = 'order_id'
    permission_required = 'pet_care_scheduler.view_schedule'

    def get_object(self, queryset=None):
        return get_object_or_404(Schedule, id=self.kwargs[self.slug_url_kwarg])


class OrderDetail(DetailView):
    model = Schedule
    template_name = 'pet_care_scheduler/order-detail.html'
    context_object_name = 'order'
    slug_url_kwarg = 'order_id'

    def get_object(self, queryset=None):
        return get_object_or_404(Schedule, id=self.kwargs[self.slug_url_kwarg])


class CompleteOrder(View):
    template_name = 'pet_care_scheduler/order-edit.html'

    def get(self, request, order_id):
        order = get_object_or_404(Schedule, id=order_id)
        context = {'order': order}
        return render(request, self.template_name, context)

    def post(self, request, order_id):
        order = get_object_or_404(Schedule, id=order_id)
        order.status = Schedule.Status.COMPLETE
        order.save()
        logger.info(f'Staff member {request.user.username} has completed an order {order.service.title}.')
        messages.success(request, "Order has been completed")
        return redirect('schedule:order_edit', order_id=order_id)


class ConfirmOrder(View):
    template_name = 'pet_care_scheduler/order-edit.html'

    def get(self, request, order_id):
        order = get_object_or_404(Schedule, id=order_id)
        context = {'order': order}
        return render(request, self.template_name, context)

    def post(self, request, order_id):
        order = get_object_or_404(Schedule, id=order_id)
        order.status = Schedule.Status.CONFIRM
        order.save()
        logger.info(f'Staff member {request.user.username} has confirmed an order {order.service.title}.')
        messages.success(request, "Order has been confirmed")
        return redirect('schedule:order_edit', order_id=order_id)


class DelayOrder(View):
    template_name = 'pet_care_scheduler/order-edit.html'

    def get(self, request, order_id):
        order = get_object_or_404(Schedule, id=order_id)
        context = {'order': order}
        return render(request, self.template_name, context)

    def post(self, request, order_id):
        order = get_object_or_404(Schedule, id=order_id)
        order.status = Schedule.Status.DELAY
        order.save()
        logger.info(f'Staff member {request.user.username} has delayed an order {order.service.title}.')
        messages.success(request, "Order has been delayed")
        return redirect('schedule:postpone_order', order_id=order_id)


class PostponeOrder(UpdateView):
    template_name = 'pet_care_scheduler/postpone_order_form.html'
    form_class = ScheduleForm
    order_id = 'order_id'

    def get_success_url(self):
        return reverse_lazy('schedule:order_edit', kwargs={'order_id': self.kwargs[self.order_id]})

    def get_object(self, queryset=None):
        return get_object_or_404(Schedule, id=self.kwargs[self.order_id])

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Edit page'
        return context


class FilterOrders(ListView):
    template_name = 'pet_care_scheduler/orders.html'
    context_object_name = 'orders'

    def get_queryset(self, queryset=None):
        service_slug = self.kwargs.get('service_slug')
        return Schedule.objects.filter(service__slug=service_slug)


class DraftOrders(ListView):
    template_name = 'pet_care_scheduler/orders.html'
    context_object_name = 'orders'

    def get_queryset(self, queryset=None):
        return Schedule.objects.filter(status=Schedule.Status.DRAFT)


class CompletedOrders(ListView):
    template_name = 'pet_care_scheduler/orders.html'
    context_object_name = 'orders'

    def get_queryset(self, queryset=None):
        return Schedule.objects.filter(status=Schedule.Status.COMPLETE)


class ConfirmedOrders(ListView):
    template_name = 'pet_care_scheduler/orders.html'
    context_object_name = 'orders'

    def get_queryset(self, queryset=None):
        return Schedule.objects.filter(status=Schedule.Status.CONFIRM)


class DelayedOrders(ListView):
    template_name = 'pet_care_scheduler/orders.html'
    context_object_name = 'orders'

    def get_queryset(self, queryset=None):
        return Schedule.objects.filter(status=Schedule.Status.DELAY)


class UserOrders(ListView):
    template_name = 'pet_care_scheduler/user_orders.html'

    def get_queryset(self, queryset=None):
        user_username = self.kwargs.get('user_username')
        user_order = get_object_or_404(get_user_model(), username=user_username)
        return Schedule.objects.filter(name=user_order)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user_username = self.kwargs.get('user_username')
        context['orders'] = self.get_queryset()
        context['user_order'] = get_object_or_404(get_user_model(), username=user_username)
        return context

src/pet_care_scheduler/templates/pet_care_scheduler/order-detail.html
{% extends 'base.html' %}

{% block content %}
<div class="card container mb-3">
    <div class="card-body my-2">
        <h3 class="card-title">service: {{ order.service }}</h3>
        <p class="card-text">nickname: {{ order.name }}</p>
        <p class="card-text">First and last name: {{ order.name.first_name }} {{ order.name.last_name }}</p>
        <p class="card-text">Phone Number: {{ order.phone_number }}</p>
        <p class="card-text">About Pet: {{ order.pet_info }}</p>
        <p class="card-text">Order date: {{ order.order_date }}</p>
        <p class="card-text">Client date for visiting: {{ order.date_for_visit }}</p>
    </div>
</div>
{% endblock %}

src/pet_care_scheduler/templates/pet_care_scheduler/order-edit.html
{% extends 'base.html' %}

{% block content %}

<div class="container">
    <div class="row">
        <div class="mx-auto">
            {% if messages %}
            {% for message in messages %}
            {% if message.level == DEFAULT_MESSAGE_LEVELS.SUCCESS %}
            <div class="alert alert-success alert-dismissible fade show" role="alert">
                {{ message }}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
            {% else %}
            <div class="alert alert-warning alert-dismissible fade show" role="alert">
                {{ message }}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
            {% endif %}
            {% endfor %}
            {% endif %}
        </div>
    </div>
</div>

<div class="card container mb-3">
    <div class="card-header">
        <ul class="nav nav-pills card-header-pills">
            <li class="nav-item mx-2">
                <form action="{% url 'schedule:complete_order' order.id %}" method="post">
                    {% csrf_token %}
                    <button class="btn btn-outline-danger" type="submit">Complete</button>
                </form>
            </li>
            <li class="nav-item mx-2">
                <form action="{% url 'schedule:confirm_order' order.id %}" method="post">
                    {% csrf_token %}
                    <button class="btn btn-success" type="submit">Confirm</button>
                </form>
            </li>
            <li class="nav-item mx-2">
                <form action="{% url 'schedule:delay_order' order.id %}" method="post">
                    {% csrf_token %}
                    <button class="btn btn-warning" type="submit">Delay</button>
                </form>
            </li>
            <li class="nav-item mx-1">
                <a class="nav-link" href="#">Link</a>
            </li>
            <li class="nav-item">
                <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
            </li>
        </ul>
    </div>

    <div class="card-body my-2">
        <h3 class="card-title">service: {{ order.service }}</h3>
        <p class="card-text">nickname: {{ order.name }}</p>
        <p class="card-text">First and last name: {{ order.name.first_name }} {{ order.name.last_name }}</p>
        <p class="card-text">Phone Number: {{ order.phone_number }}</p>
        <p class="card-text">About Pet: {{ order.pet_info }}</p>
        <p class="card-text">Order date: {{ order.order_date }}</p>
        <p class="card-text">Client date for visiting: {{ order.date_for_visit }}</p>
        <a href="{% url 'schedule:show_orders' %}" class="btn btn-primary">Go somewhere</a>
    </div>
</div>

{% endblock %}

src/pet_care_scheduler/templates/pet_care_scheduler/orders.html
{% extends "base.html" %}

{% block content %}
<div class="vet-consultations__title container">
    <h1>Orders</h1>
</div>


<ul class="nav nav-tabs container mb-5 fs-5">
    <li class="nav-item">
        <a class="nav-link active" aria-current="page" href="{% url 'schedule:show_orders' %}">All</a>
    </li>
    <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-expanded="false">Services</a>
        <ul class="dropdown-menu">
            {% for service in services_list %}
            <li>
                <a class="dropdown-item" href="{% url 'schedule:show_filter_orders' service.slug %}">{{ service.title }}</a>
            </li>
            {% endfor %}
            <li>
                <hr class="dropdown-divider">
            </li>
            <li><a class="dropdown-item" href="#">#</a></li>
        </ul>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="{% url 'schedule:draft_orders' %}">Draft</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="{% url 'schedule:completed_orders' %}">Completed</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="{% url 'schedule:confirmed_orders' %}">Confirmed</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="{% url 'schedule:delayed_orders' %}">Postponed</a>
    </li>
    <li class="nav-item">
        <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
    </li>
</ul>


{% for order in orders %}
<div class="card {% if order.status == 'CMP' %}border-danger{% elif order.status == 'CNF' %}border-success{% elif order.status == 'DLY' %}border-warning{% else %}border-primary{% endif %} border-3 container mb-3">
    <div class="card-body my-2">
        <h3 class="card-title">service: <a href="{{ order.get_absolute_url }}">{{ order.service }}</a></h3>
        <p class="card-text">nickname: {{ order.name }}</p>
        <p class="card-text">First and last name: {{ order.name.first_name }} {{ order.name.last_name }}</p>
        <p class="card-text">Phone Number: {{ order.phone_number }}</p>
        <p class="card-text">About Pet: {{ order.pet_info }}</p>
        <p class="card-text">Order date: {{ order.order_date }}</p>
        <p class="card-text">Client date for visiting: {{ order.date_for_visit }}</p>
        <a href="{% url 'schedule:order_edit' order.id %}" class="btn btn-primary">Details</a>
    </div>
</div>
{% endfor %}

{% endblock %}

src/pet_care_scheduler/templates/pet_care_scheduler/postpone_order_form.html
{% extends "base.html" %}

{% block content %}
<div class="vet-consultations__title container">
    <h1>Edit your account</h1>
</div>

<form class="container" action="#" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="row mb-3">
        <label class="col-sm-2 col-form-label">Phone number</label>
        <div class="col-sm-10">
            <p>{{ form.phone_number }}</p>
        </div>
        <label class="col-sm-2 col-form-label">Information about pet:</label>
        <div class="col-sm-10">
            <p>{{ form.pet_info }}</p>
        </div>
        <label class="col-sm-2 col-form-label my-4">Date for visit:</label>
        <div class="col-sm-10">
            <p>{{ form.date_for_visit }}</p>
        </div>
    </div>
    <div class="contacts-form__field">
        <input type="hidden" name="next" value="{{ next }}"/>
        <button class="contacts-form__button" type="submit">Edit</button>
    </div>
    <!--    <button type="submit" class="btn btn-primary">Edit</button>-->
</form>
{% endblock %}

src/pet_care_scheduler/templates/pet_care_scheduler/user_orders.html
{% extends "base.html" %}

{% block content %}
<div class="vet-consultations__title container">
    <h1>My Orders</h1>
</div>

{% if request.user.username ==  user_order.username %}
{% for order in orders %}
<div class="card container mb-3">
    <div class="card-header">
        <ul class="nav nav-pills card-header-pills">
            <li class="nav-item">
                <a class="nav-link active" href="#">Active</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">Link</a>
            </li>
            <li class="nav-item">
                <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
            </li>
        </ul>
    </div>
    <div class="card-body my-2">
        <h3 class="card-title">service: <a href="{{ order.get_absolute_url }}">{{ order.service }}</a></h3>
        <p class="card-text">nickname: {{ order.name }}</p>
        <p class="card-text">First and last name: {{ order.name.first_name }} {{ order.name.last_name }}</p>
        <p class="card-text">Phone Number: {{ order.phone_number }}</p>
        <p class="card-text">About Pet: {{ order.pet_info }}</p>
        <p class="card-text">Order date: {{ order.order_date }}</p>
        <p class="card-text">Client date for visiting: {{ order.date_for_visit }}</p>
    </div>
</div>
{% endfor %}
{% endif %}
{% endblock %}