src/accounts/urls.py
from django.contrib.auth.views import PasswordChangeDoneView, PasswordResetView, PasswordResetDoneView, \
    PasswordResetConfirmView, PasswordResetCompleteView
from django.urls import path, reverse_lazy
from . import views

app_name = 'accounts'

urlpatterns = [
    path('login/', views.LoginUser.as_view(), name='login'),
    path('logout/', views.LogoutUser.as_view(), name='logout'),

    path('register/', views.register, name='register'),

    path('password-change/', views.UserChangePassword.as_view(), name='password_change'),
    path('password-change_done/', PasswordChangeDoneView.as_view(template_name='accounts/password_change_done.html'),
         name='password_change_done'),

    path('password-reset/', PasswordResetView.as_view(
        template_name='accounts/password_reset_form.html',
        email_template_name='accounts/password_reset_email.html',
        success_url=reverse_lazy('accounts:password_reset_done')
    ), name='password_reset'),
    path('password-reset/done/', PasswordResetDoneView.as_view(template_name='accounts/password_reset_done.html'),
         name='password_reset_done'),
    path('password-reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(
        template_name='accounts/password_reset_form.html',
        success_url=reverse_lazy('accounts:password_reset_complete')
    ), name='password_reset_confirm'),
    path('password-reset/complete/', PasswordResetCompleteView.as_view(template_name='accounts/password_reset_complete.html'),
         name='password_reset_complete'),

    path('edit/', views.edit, name='edit'),

    path('profile/<str:user_username>/', views.profile_to_view, name='profile_to_view'),
]

src/blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.BlogView.as_view(), name='blog'),
    path('posts/<slug:blog_slug>/', views.BlogDetailView.as_view(), name='blog_detail'),
    path('posts/category/<slug:category_blog_slug>/', views.CategoryBlogView.as_view(), name='category_blog'),
    path('like/', views.post_like, name='post_like'),
]

src/pet_care_scheduler/urls.py
from django.urls import path
from . import views

app_name = 'schedule'

urlpatterns = [
    # path('orders/confirmed/<slug:service_slug>/', views.confirm_filter_orders, name='confirm_filter_orders'),
    path('orders/draft/', views.DraftOrders.as_view(), name='draft_orders'),
    path('orders/completed/', views.CompletedOrders.as_view(), name='completed_orders'),
    path('orders/confirmed/', views.ConfirmedOrders.as_view(), name='confirmed_orders'),
    path('orders/postponed/', views.DelayedOrders.as_view(), name='delayed_orders'),
    path('orders/', views.ShowOrders.as_view(), name='show_orders'),
    path('user-orders/<str:user_username>/', views.UserOrders.as_view(), name='show_user_orders'),
    path('orders/detail/<int:order_id>/', views.OrderDetail.as_view(), name='order_detail'),
    path('orders/edit/<int:order_id>/', views.OrderEdit.as_view(), name='order_edit'),
    path('orders/<int:order_id>/complete/', views.CompleteOrder.as_view(), name='complete_order'),
    path('orders/<int:order_id>/confirm/', views.ConfirmOrder.as_view(), name='confirm_order'),
    path('orders/<int:order_id>/delay/', views.DelayOrder.as_view(), name='delay_order'),
    path('orders/<int:order_id>/postpone/', views.PostponeOrder.as_view(), name='postpone_order'),
    path('orders/<slug:service_slug>/', views.FilterOrders.as_view(), name='show_filter_orders'),
]

src/project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('vet_clinic.urls', namespace='vet_clinic')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('schedule/', include('pet_care_scheduler.urls', namespace='schedule')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('__debug__/', include('debug_toolbar.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/accounts/models.py
from django.conf import settings
from django.db import models


class Profile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    date_of_birth = models.DateField(null=True, blank=True)
    photo = models.ImageField(upload_to='accounts/%Y/%m/%d/', blank=True)
    send_mail = models.BooleanField(default=False)

    def __str__(self):
        return f'Profile of {self.user.username}'


class StaffProfile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    position = models.CharField(max_length=255, null=True, blank=True)
    description = models.TextField(null=True, blank=True)

    def __str__(self):
        return f'StaffProfile of {self.user.username}'

src/pet_care_scheduler/models.py
from django.conf import settings
from django.db import models
from django.urls import reverse
from phonenumber_field.modelfields import PhoneNumberField

from vet_clinic.models import Service


class Schedule(models.Model):
    class Status(models.TextChoices):
        DRAFT = 'DRF', 'Draft'
        COMPLETE = 'CMP', 'Complete'
        CONFIRM = 'CNF', 'Confirm'
        DELAY = 'DLY', 'Delay'

    name = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='client_name')
    phone_number = PhoneNumberField()
    pet_info = models.CharField(max_length=50)
    service = models.ForeignKey(Service, on_delete=models.CASCADE, related_name='service_name')
    order_date = models.DateTimeField(auto_now_add=True)
    date_for_visit = models.DateField()
    status = models.CharField(max_length=3, choices=Status.choices, default=Status.DRAFT)

    class Meta:
        verbose_name = 'Schedule'
        verbose_name_plural = 'Schedule'
        ordering = ['-order_date']
        indexes = [
            models.Index(fields=['-order_date']),
        ]

    def get_absolute_url(self):
        return reverse("schedule:order_detail", kwargs={"order_id": self.id})

    def __str__(self):
        return f'Order by {self.name}'

src/accounts/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import PasswordChangeForm
from django.forms import ClearableFileInput

from accounts.models import Profile, StaffProfile


class UserRegistrationForm(forms.ModelForm):
    password = forms.CharField(label='Password', widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    password2 = forms.CharField(label='Repeat password', widget=forms.PasswordInput(attrs={'class': 'form-control'}))

    class Meta:
        model = get_user_model()
        fields = ['username', 'email', 'first_name', 'last_name']
        widgets = {
            'username': forms.TextInput(
                attrs={'class': 'form-control'}),
            'email': forms.TextInput(
                attrs={'class': 'form-control'}),
            # 'password': forms.TextInput(
            #     attrs={'class': 'form-control', "id":"floatingPassword"}),
            # 'password2': forms.PasswordInput(
            #     attrs={'class': 'form-control'}),
            'first_name': forms.TextInput(
                attrs={'class': 'form-control'}),
            'last_name': forms.TextInput(
                attrs={'class': 'form-control'}),
        }

    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password'] != cd['password2']:
            raise forms.ValidationError('Passwords don\'t match.')
        return cd['password2']

    def clean_email(self):
        email = self.cleaned_data['email']
        if get_user_model().objects.filter(email=email).exists():
            raise forms.ValidationError('Email already exists')
        return email


class UserChangePasswordForm(PasswordChangeForm):
    old_password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    new_password1 = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    new_password2 = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}))


class UserEditForm(forms.ModelForm):
    class Meta:
        model = get_user_model()
        fields = ['first_name', 'last_name', 'email']
        widgets = {
            # 'name': forms.TextInput(
            #     attrs={'class': 'contacts-form__input-name', 'placeholder': 'Enter your full name'}),
            'first_name': forms.TextInput(
                attrs={'class': 'form-control'}),
            'last_name': forms.TextInput(
                attrs={'class': 'form-control'}),
        }

    def clean_email(self):
        data = self.cleaned_data['email']
        qs = get_user_model().objects.exclude(id=self.instance.id) \
            .filter(email=data)
        if qs.exists():
            raise forms.ValidationError('Email already in use.')
        return data


class CustomClearableFileInput(ClearableFileInput):
    template_name = 'vet_clinic/widgets/custom_clearable_file_input.html'


class ProfileEditForm(forms.ModelForm):
    date_of_birth = forms.DateField(widget=forms.widgets.DateInput(attrs={'class': 'contacts-form__input-service',
                                                                          'type': 'date'}))

    class Meta:
        model = Profile
        fields = ['date_of_birth', 'photo', 'send_mail']
        widgets = {
            'photo': CustomClearableFileInput(
                attrs={'class': 'form-control'}),
        }


class StaffProfileEditForm(forms.ModelForm):
    class Meta:
        model = StaffProfile
        fields = ['position', 'description']
        widgets = {
            'position': forms.TextInput(
                attrs={'class': 'form-control'}),
            'description': forms.Textarea(
                attrs={'class': 'form-control'})
        }

src/accounts/views.py
import logging

from django.contrib import messages
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.models import User, Group
from django.contrib.auth.views import LoginView, LogoutView, PasswordChangeView
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse_lazy

from accounts.forms import UserRegistrationForm, UserChangePasswordForm, UserEditForm, ProfileEditForm, \
    StaffProfileEditForm
from accounts.models import Profile, StaffProfile
from actions.models import Actions
from actions.utils import create_action

logger = logging.getLogger('accounts')


class MyCustomLoginForm(AuthenticationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'contacts-form__input-name'


class LoginUser(LoginView):
    form_class = MyCustomLoginForm
    template_name = 'accounts/login.html'

    def form_valid(self, form):
        username = form.cleaned_data.get('username')
        logger.info(f'User {username} has logged in')
        return super().form_valid(form)


class LogoutUser(LogoutView):
    template_name = 'accounts/logout.html'
    extra_context = {'title': 'Logout'}

    def dispatch(self, request, *args, **kwargs):
        username = request.user.username
        logger.info(f'User {username} has logged out.')
        return super().dispatch(request, *args, **kwargs)


def register(request):
    if request.method == 'POST':
        form = UserRegistrationForm(request.POST)
        if form.is_valid():
            new_user = form.save(commit=False)
            new_user.set_password(form.cleaned_data['password'])
            new_user.save()
            Profile.objects.create(user=new_user)
            StaffProfile.objects.create(user=new_user)
            create_action(new_user, 'has created an account')
            logger.info(f'User {form.cleaned_data["username"]} has registered.')
            return render(request, 'accounts/register_done.html', {'new_user': new_user})
    else:
        form = UserRegistrationForm()

    return render(request, 'accounts/register.html', {'form': form})


class UserChangePassword(PasswordChangeView):
    form_class = UserChangePasswordForm
    template_name = 'accounts/password_change_form.html'
    success_url = reverse_lazy('accounts:password_change_done')

    def dispatch(self, request, *args, **kwargs):
        username = request.user.username
        logger.info(f'User {username} has changed password.')
        return super().dispatch(request, *args, **kwargs)


@login_required
def edit(request):
    if request.method == 'POST':
        user_form = UserEditForm(instance=request.user, data=request.POST)
        profile_form = ProfileEditForm(instance=request.user.profile, data=request.POST, files=request.FILES)
        staff_profile_form = None
        if request.user.groups.filter(name='moderator').exists():
            staff_profile_form = StaffProfileEditForm(instance=request.user.staffprofile, data=request.POST)
        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
        if staff_profile_form and staff_profile_form.is_valid():
            staff_profile_form.save()
        logger.info(f'User {request.user.username} has edited profile.')
        return redirect('accounts:edit')
            # messages.success(request, 'Profile updated successfully')
        # else:
        # messages.error(request, 'Error updating your profile')
    else:
        user_form = UserEditForm(instance=request.user)
        profile_form = ProfileEditForm(instance=request.user.profile)
        staff_profile_form = None
        if request.user.groups.filter(name='moderator').exists():
            staff_profile_form = StaffProfileEditForm(instance=request.user.staffprofile)

    data = {
        'user_form': user_form,
        'profile_form': profile_form,
        'staff_profile_form': staff_profile_form
    }

    return render(request, 'accounts/edit.html', context=data)


def profile_to_view(request, user_username):
    user_to_view = get_object_or_404(User, username=user_username)
    actions = Actions.objects.filter(user=request.user)

    data = {
        'user_to_view': user_to_view,
        'actions': actions
    }

    return render(request, 'accounts/profile.html', context=data)

src/accounts/templates/accounts/edit.html
{% extends "base.html" %}

{% block content %}
<div class="vet-consultations__title container">
    <h1>Edit your account</h1>
</div>

<form class="container" action="#" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="row mb-3">
        <label class="col-sm-2 col-form-label">First name</label>
        <div class="col-sm-10">
            <p>{{ user_form.first_name }}</p>
        </div>
        <label class="col-sm-2 col-form-label">Last name</label>
        <div class="col-sm-10">
            <p>{{ user_form.last_name }}</p>
        </div>
        <label class="col-sm-2 col-form-label my-4">Date of birth</label>
        <div class="col-sm-10">
            <p>{{ profile_form.date_of_birth }}</p>
        </div>
    </div>
    <div class="row mb-3">
        <div class="input-group mb-3">
            <label class="col-sm-2 col-form-label my-4">Photo</label>
            <div class="card" style="width: 18rem;">
                {% if profile_form.photo.value %}
                <img src="{{ profile_form.photo.value.url }}" class="card-img-top" alt="...">
                {% endif %}
                <div class="card-body">
                    <h5 class="card-title">Change photo</h5>
                    <p class="card-text">Choose photo</p>
                    <p>{{ profile_form.photo }}</p>
                </div>
            </div>
        </div>
        <label class="col-sm-2 col-form-label">Send mail</label>
        <div class="col-sm-10">
            <p>{{ profile_form.send_mail }}</p>
        </div>
    </div>
     {% if staff_profile_form %}
    <div class="row mb-3">
        {% if perms.pet_care_scheduler.view_schedule %}
        <label class="col-sm-2 col-form-label">Position</label>
        <div class="col-sm-10">
            <p>{{ staff_profile_form.position }}</p>
        </div>
        {% endif %}
        {% if perms.pet_care_scheduler.view_schedule %}
        <label class="col-sm-2 col-form-label">Description</label>
        <div class="col-sm-10">
            <p>{{ staff_profile_form.description }}</p>
        </div>
        {% endif %}
    </div>
    {% endif %}
    <div class="contacts-form__field">
        <input type="hidden" name="next" value="{{ next }}"/>
        <button class="contacts-form__button" type="submit">Edit</button>
    </div>
    <!--    <button type="submit" class="btn btn-primary">Edit</button>-->
</form>
{% endblock %}

src/accounts/templates/accounts/login.html
{% extends 'base.html' %}

{% block content %}
<div class="vet-consultations__title container">
    <h1>Login</h1>
</div>
<div class="contacts-help-section__form-container ">
    <div class="contacts-help-section__wrapper">
        <form class="contacts-form" action="#" method="post">
            <div class="responses__form-title">
                <h3>Use the following form to login</h3>
            </div>
            <div class="contacts-form__field">
                <div class="contacts-form__field">
                    {{ form.as_p }}
                    {% csrf_token %}
                </div>
            </div>
            <div class="contacts-form__field">
                <input type="hidden" name="next" value="{{ next }}"/>
                <button class="contacts-form__button" type="submit">Login</button>
            </div>
        </form>
    </div>
</div>

{% endblock %}

src/accounts/templates/accounts/logout.html
{% extends 'base.html' %}

{% block content %}
<div class="vet-consultations__title container">
    <h1>Logged out</h1>
</div>
<div class="contacts-help-section__form-container ">
    <div class="contacts-help-section__wrapper">
        <div class="responses__form-title">
            <h3>You have been successfully logged out.
                You can <a href="{% url 'accounts:login' %}">log in again</a></h3>
        </div>
    </div>
</div>
{% endblock %}

src/accounts/templates/accounts/password_change_done.html
{% extends 'base.html' %}

{% block content %}
<h1>Password changed</h1>
<p>Your password has been successfully changed.</p>
{% endblock %}

src/accounts/templates/accounts/password_change_form.html
{% extends 'base.html' %}

{% block content %}
<div class="vet-consultations__title container">
    <h1>Change your password</h1>
</div>

<form class="container" action="#" method="post">
    {% csrf_token %}
    <div class="row mb-3">
        <label class="col-sm-2 col-form-label">Old password</label>
        <div class="col-sm-10">
            <p>{{ form.old_password }}</p>
        </div>
        <label class="col-sm-2 col-form-label">New password</label>
        <div class="col-sm-10">
            <p>{{ form.new_password1 }}</p>
        </div>
        <label class="col-sm-2 col-form-label">Repeat password</label>
        <div class="col-sm-10">
            <p>{{ form.new_password2 }}</p>
        </div>
    </div>

    <div class="contacts-form__field">
        <input type="hidden" name="next" value="{{ next }}"/>
        <button class="contacts-form__button" type="submit">Edit</button>
    </div>
    <!--    <button type="submit" class="btn btn-primary">Edit</button>-->
</form>
{% endblock %}

src/accounts/templates/accounts/password_reset_complete.html
{% extends "base.html" %}

{% block content %}
<div class="vet-consultations__title container">
    <h1>Password set</h1>
</div>
<div class="contacts-help-section__form-container ">
    <div class="contacts-help-section__wrapper">
        <div class="responses__form-title">
            <h3>Re-login.</h3>
            <p>Your password has been set. You can <a href="{% url 'accounts:login' %}">log in now</a></p>
        </div>
    </div>
</div>
{% endblock %}

src/accounts/templates/accounts/password_reset_confirm.html
{% extends "base.html" %}

{% block content %}
<h1>Reset your password</h1>
{% if validlink %}
<p>Please enter your new password twice:</p>
<form method="post">
    {{ form.as_p }}
    {% csrf_token %}
    <p><input type="submit" value="Change my password"/></p>
</form>
{% else %}
<p>The password reset link was invalid, possibly because it has already
    been used. Please request a new password reset.</p>
{% endif %}
{% endblock %}

src/accounts/templates/accounts/password_reset_done.html
{% extends "base.html" %}

{% block content %}
<div class="vet-consultations__title container">
    <h1>Reset your password</h1>
</div>
<div class="contacts-help-section__form-container ">
    <div class="contacts-help-section__wrapper">
        <div class="responses__form-title">
            <h3>We've emailed you instructions for setting your password.</h3>
            <p>If you don't receive an email, please make sure
                you've entered the address you registered with.</p>
        </div>
    </div>
</div>
{% endblock %}

src/accounts/templates/accounts/password_reset_email.html
Someone asked for password reset for email {{ email }}.
Follow the link below: {{ protocol }}://{{ domain }}{% url "accounts:password_reset_confirm" uidb64=uid token=token %}
Your username, in case you've forgotten: {{ user.get_username }}

src/accounts/templates/accounts/password_reset_form.html
{% extends "base.html" %}

{% block content %}
<div class="vet-consultations__title container">
    <h1>Forgotten your password?</h1>
</div>
<div class="contacts-help-section__form-container ">
    <div class="contacts-help-section__wrapper">
        <form class="contacts-form" action="#" method="post">
            <div class="responses__form-title">
                <h3>Enter your e-mail address to obtain a new password.</h3>
            </div>
            <div class="contacts-form__field">
                <div class="contacts-form__field">
                    {{ form.as_p }}
                    {% csrf_token %}
                </div>
            </div>
            <div class="contacts-form__field">
                <input type="hidden" name="next" value="{{ next }}"/>
                <button class="contacts-form__button" type="submit">Send e-mail</button>
            </div>
        </form>
    </div>
</div>
{% endblock %}

src/accounts/templates/accounts/profile.html
{% extends "base.html" %}

{% block content %}
<div class="vet-consultations__title container">
    <h1>{{ user_to_view.username }}'s Profile</h1>
</div>


<div class="d-flex flex-row bd-highlight mb-3 container">
    <div class="card"
         style="width: 18rem; color: var(--link-text-color); background-color: var(--button-background-light-color)">
        {% if user_to_view.profile.photo %}
        <img src="{{ user_to_view.profile.photo.url }}" class="card-img-top" alt="...">
        {% endif %}
        <div class="card-body">
            <h5 class="card-title">{{ user_to_view.username }}</h5>
            <p class="card-text">{{ user_to_view.first_name }} {{ user_to_view.last_name }}</p>
            <a href="#" class="btn btn-primary">Go somewhere</a>
        </div>
    </div>
    {% if request.user.username == user_to_view.username %}
    <ul class="list-group mx-3 container">
        <li class="list-group-item"
            style="background-color: var(--button-background-light-color)">
            {% if perms.pet_care_scheduler.view_schedule %}
            <a href="{% url 'schedule:show_orders' %}"
               style="text-decoration: none; border-bottom: 1px solid var(--link-text-color);color: var(--link-text-color);">
                Orders
            </a>
            {% endif %}
        </li>
        <li class="list-group-item"
            style="background-color: var(--button-background-light-color)">
            <a href="{% url 'schedule:show_user_orders' user_username=request.user.username %}"
               style="text-decoration: none; border-bottom: 1px solid var(--link-text-color);color: var(--link-text-color);">
                My Orders
            </a>
        </li>
        <li class="list-group-item"
            style="background-color: var(--button-background-light-color)">
            <a href="{% url 'accounts:password_change' %}" style="text-decoration: none; border-bottom: 1px solid var(--link-text-color);color: var(--link-text-color);">
                Change password
            </a>
        </li>
    </ul>
    {% endif %}
</div>
<div class="container mx-auto">
    <h2>Your actions</h2>
    <div id="action-list">
        {% for action in actions %}
        {% include "actions/detail.html" %}
        {% endfor %}
    </div>
</div>
{% endblock %}

src/accounts/templates/accounts/register.html
{% extends "base.html" %}

{% block content %}
<div class="vet-consultations__title container">
    <h1>Create an account</h1>
</div>

<form class="container" action="#" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="row mb-3">
        <label class="col-sm-2 col-form-label">Username</label>
        <div class="col-sm-10">
            <p>{{ form.username }}</p>
        </div>
        <label class="col-sm-2 col-form-label">Email</label>
        <div class="col-sm-10">
            <p>{{ form.email }}</p>
        </div>
        <label class="col-sm-2 col-form-label">Password</label>
        <div class="col-sm-10">
            <p>{{ form.password }}</p>
        </div>
        <label class="col-sm-2 col-form-label">Repeat password</label>
        <div class="col-sm-10">
            <p>{{ form.password2 }}</p>
        </div>
        <label class="col-sm-2 col-form-label">First name</label>
        <div class="col-sm-10">
            <p>{{ form.first_name }}</p>
        </div>
        <label class="col-sm-2 col-form-label">Last name</label>
        <div class="col-sm-10">
            <p>{{ form.last_name }}</p>
        </div>
        <div class="contacts-form__field">
            <input type="hidden" name="next" value="{{ next }}"/>
            <button class="contacts-form__button" type="submit">Register</button>
        </div>
    </div>
</form>
{% endblock %}

src/accounts/templates/accounts/register_done.html
{% extends "base.html" %}

{% block content %}


<div class="vet-consultations__title container">
    <h1>Welcome {{ new_user.first_name }}!</h1>
</div>
<div class="contacts-help-section__form-container ">
    <div class="contacts-help-section__wrapper">
        <div class="responses__form-title">
            <h3>
                Your account has been successfully created.
                Now you can <a href="{% url 'accounts:login' %}">log in</a>.
            </h3>
        </div>
    </div>
</div>
{% endblock %}